version: "3"

services:
    mediawiki:
        image: supreetraut/mediawiki-1.34
        container_name: mediawiki
        restart: always
        ports:
            - "8000:80"
        networks:
            - wikinetwork
    db:
        image: supreetraut/mariadb-wiki
        container_name: db
        restart: always
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
        ports:
            - "33060:3306"
        networks:
            - wikinetwork

networks:
    wikinetwork:
        driver: bridge
